export enum Type {
    SIGNED_CHAR = "a",
    BOOL = "b",
    CHAR = "c",
    DOUBLE = "d",
    LONG_DOUBLE = "e",
    FLOAT = "f",
    FLOAT128 = "g",
    UNSIGNED_CHAR = "h",
    INT = "i",
    UNSIGNED_INT = "j",
    LONG = "l",
    UNSIGNED_LONG = "m",
    INT128 = "n",
    UNSIGNED_INT128 = "o",
    SHORT = "s",
    STD__ALLOCATOR = "Sa",
    STD__BASIC_STRING = "Sb",
    STD__STRING = "Ss",
    STD = "St",
    UNSIGNED_SHORT = "t",
    VOID = "v",
    WCHAR_T = "w",
    LONG_LONG = "x",
    UNSIGNED_LONG_LONG = "y",
    ELLIPSIS = "z"
}