export const TYPES = new Map([
    [ 'a', 'signed char' ],
    [ 'b', 'bool' ],
    [ 'c', 'char' ],
    [ 'd', 'double' ],
    [ 'e', 'long double' ],
    [ 'f', 'float' ],
    [ 'g', 'float128' ],
    [ 'h', 'unsigned char' ],
    [ 'i', 'int' ],
    [ 'j', 'unsigned int' ],
    [ 'l', 'long' ],
    [ 'm', 'unsigned long' ],
    [ 'n', 'int128' ],
    [ 'o', 'unsigned int128' ],
    [ 's', 'short' ],
    [ 'Sa', 'std::allocator' ],
    [ 'Sb', 'std::basic_string' ],
    [ 'Sd', 'std::basic_iostream' ],
    [ 'Si', 'std::basic_istream' ],
    [ 'So', 'std::basic_ostream' ],
    [ 'Ss', 'std::string' ],
    [ 'St', 'std' ],
    [ 't', 'unsigned short' ],
    [ 'v', 'void' ],
    [ 'w', 'wchar_t' ],
    [ 'x', 'long long' ],
    [ 'y', 'unsigned long long' ],
    [ 'z', '...' ]
]);